// Pretendard 는 android에서 font-weight 를 설정했을 경우 먹히지 않는 이슈가 있어서 뺐습니다.
export const fonts = {
  title: {
    m26: 'font-family:"Pretendard-Regular"; font-size: 26px;line-height: 31px;',
    b30: 'font-family:"Pretendard-Bold"; font-size: 30px; line-height: 40px;',
    b26: 'font-family:"Pretendard-SemiBold"; font-size: 26px; line-height: 36px;',
    b24: 'font-family:"Pretendard-Bold"; font-size: 24px; line-height: 30px;',
    m24: 'font-family: "Pretendard-Medium"; font-size:24px; line-height: 30px;',
    b22: 'font-family:"Pretendard-Bold"; font-size: 22px; line-height: 30px;',
    m22: 'font-family:"Pretendard-SemiBold"; font-size: 22px; line-height: 30px;',
    l22: 'font-family:"Pretendard-Medium"; font-size: 22px; line-height: 30px;',
    b20: 'font-family:"Pretendard-Bold"; font-size: 20px; line-height: 24px;',
    m20: 'font-family:"Pretendard-SemiBold"; font-size: 20px; line-height: 30px;',
    b18: 'font-family:"Pretendard-Bold"; font-size: 18px; line-height: 22px;',
    m44: 'font-family:"Pretendard-Medium"; font-size: 44px; line-height: 52px;',
  },
  subTitle: {
    m20: 'font-family: "Pretendard-Regular"; font-size: 20px; line-height: 24px;',
    b17: 'font-family:"Pretendard-Bold"; font-size: 17px; line-height: 24px;',
    b18: 'font-family:"Pretendard-Bold"; font-size: 18px; line-height: 22px;',
    m18: 'font-family: "Pretendard-Medium"; font-size: 18px; line-height: 22px;',
    b16: 'font-family: "Pretendard-Bold"; font-size: 16px; line-height: 20px;',
  },
  card: {
    b15: 'font-family: "Pretendard-SemiBold"; font-size: 15px; line-height: 17px;',
    b14: 'font-family: "Pretendard-Bold"; font-size: 14px; line-height: 17px;',
    m14: 'font-family: "Pretendard-SemiBold"; font-size: 14px; line-height: 17px;',
    l14: 'font-family: "Pretendard-Regular"; font-size: 14px; line-height: 17px;',
    b13: 'font-family: "Pretendard-Bold"; font-size: 13px; line-height: 16px;',
    m13: 'font-family: "Pretendard-SemiBold"; font-size: 13px; line-height: 16px;',
    l13: 'font-family: "Pretendard-Regular"; font-size: 13px; line-height: 16px;',
    b12: 'font-family: "Pretendard-Bold"; font-size: 12px; line-height: 14px;',
    b11: 'font-family: "Pretendard-Bold"; font-size: 11px; line-height: 14px;',
    m11: 'font-family: "Pretendard-SemiBold"; font-size: 11px; line-height: 14px;',
  },
  body: {
    b11: 'font-family: "Pretendard-Bold"; font-size: 11px; line-height: 14px;',
    b12: 'font-family: "Pretendard-Bold"; font-size: 12px; line-height: 14px;',
    b13: 'font-family: "Pretendard-Bold"; font-size: 13px; line-height: 18px;',
    b14: 'font-family: "Pretendard-Bold"; font-size: 14px; line-height: 20px;',
    b15: 'font-family: "Pretendard-SemiBold"; font-size: 15px; line-height: 22px;',
    b16: 'font-family: "Pretendard-SemiBold"; font-size: 16px; line-height: 22px;',
    b17: 'font-family: "Pretendard-Bold"; font-size: 17px; line-height: 24px;',
    b18: 'font-family: "Pretendard-SemiBold"; font-size: 18px; line-height: 26px;',
    b20: 'font-family: "Pretendard-Bold"; font-size: 20px; line-height: 22px;',
    l11: 'font-family: "Pretendard-Regular"; font-size: 11px; line-height: 14px;',
    l12: 'font-family: "Pretendard-Regular"; font-size: 12px; line-height: 14px;',
    l13: 'font-family: "Pretendard-Regular"; font-size: 13px; line-height: 18px;',
    l14: 'font-family: "Pretendard-Regular"; font-size: 14px; line-height: 20px;',
    l15: 'font-family: "Pretendard-Regular"; font-size: 15px; line-height: 22px;',
    l16: 'font-family: "Pretendard-Regular"; font-size: 16px; line-height: 22px;',
    l17: 'font-family: "Pretendard-Regular"; font-size: 17px; line-height: 24px;',
    l18: 'font-family: "Pretendard-Regular"; font-size: 18px; line-height: 26px;',
    m10: 'font-family: "Pretendard-Regular"; font-size: 10px; line-height: 14px;',
    m11: 'font-family: "Pretendard-Medium"; font-size: 11px; line-height: 14px;',
    m12: 'font-family: "Pretendard-Medium"; font-size: 12px; line-height: 14px;',
    m13: 'font-family: "Pretendard-Medium"; font-size: 13px; line-height: 18px;',
    m14: 'font-family: "Pretendard-Medium"; font-size: 14px; line-height: 20px;',
    m15: 'font-family: "Pretendard-Medium"; font-size: 15px; line-height: 22px;',
    m16: 'font-family: "Pretendard-Medium"; font-size: 16px; line-height: 22px;',
    m17: 'font-family: "Pretendard-Medium"; font-size: 17px; line-height: 24px;',
    m9: 'font-family: "Pretendard-Medium"; font-size: 9px; line-height: 14px;',
  },
  menu: {
    b10: 'font-family: "Pretendard-SemiBold"; font-size: 10px; line-height: 10px;',
    m10: 'font-family: "Pretendard-Medium"; font-size: 10px; line-height: 10px;',
  },
  banner: {
    m36: 'font-family: "Pretendard-Medium"; font-size: 36px; line-height: 44px;',
    m26: 'font-family: "Pretendard-Medium"; font-size: 26px; line-height: 36px;',
  },
};
